name: UFT Auto
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: self-runner-node
    steps:
      - name: "Trigger jenkins job"
        uses: sudheendragopal/Jenkins_Demo@main
        with:
          jenkins-url: "https://agis-jenkins.appfuxion.com/"
          user: "admin"
          jenkins-token: "11dd2db143b88417b4084c0e69c125940c"
          job-name: "UFT_Test_03"
          job-params: '{"branch_name": "${{github.ref}}"}'
